name: Lint and test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    container:
      image: node:alpine

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn run lint:ci --max-warnings 1

  tests:
    needs: [lint]
    name: Tests
    runs-on: ubuntu-latest

    container:
      image: node:alpine

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn run test

  build:
    needs: [lint, tests]
    name: Build
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    container:
      image: node:alpine

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn run build
